/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "dwmc.c"
#include "shiftviewclients.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_gapplessgrid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"
